test
hashicorp/terraform-azurerm-terraform-enterprise pull request #114
Opened 2021-07-22 19:05 UTC by anniehedgpeth

## Background

This is just an empty commit to test the previously merged workflows. No need for reviews.

2021-07-22 19:06 UTC, anniehedgpeth commented
/help

2021-07-22 20:04 UTC, anniehedgpeth commented
/help

2021-07-22 20:11 UTC, anniehedgpeth commented
/help

2021-07-22 20:12 UTC, anniehedgpeth commented
/test all

2021-07-22 20:15 UTC, anniehedgpeth commented
/test public-active-active

2021-07-22 20:19 UTC, anniehedgpeth commented
/test all

2021-07-22 21:59 UTC, anniehedgpeth commented
So @aaron-lane, the public test currently uses a self-signed cert, which was intentional because I wanted to also test that logic. But that means that I'd need to add the -k flag for the curls. Is that a problem? If not, this will be a real PR as I committed that change [here](https://github.com/hashicorp/terraform-azurerm-terraform-enterprise/pull/114/commits/5b863c6d23012d67529d8405e60e7226a8d0a1c4).

The only other changes are bumping the AzureRM provider version (@sandrampeter had done this on some of the modules already, but I just finished it out). And it updates the README from the copy/pasta mistake in pre-reqs.

2021-07-23 13:47 UTC, aaron-lane commented
> So @aaron-lane, the public test currently uses a self-signed cert, which was intentional because I wanted to also test that logic. But that means that I'd need to add the -k flag for the curls. Is that a problem? If not, this will be a real PR as I committed that change [here](https://github.com/hashicorp/terraform-azurerm-terraform-enterprise/pull/114/commits/5b863c6d23012d67529d8405e60e7226a8d0a1c4).

@anniehedgpeth That should be fine while we wait for the trusted certificate to be provisioned. ✅

2021-08-16 18:25 UTC, anniehedgpeth commented
/test public-active-active

2021-08-16 20:43 UTC, anniehedgpeth commented
/test all

2021-08-16 20:51 UTC, anniehedgpeth commented
/test all

2021-08-17 20:45 UTC, anniehedgpeth commented
/test all

2021-08-21 00:21 UTC, anniehedgpeth commented
/test all

2021-08-21 00:25 UTC, anniehedgpeth commented
/test all

2021-08-23 14:40 UTC, anniehedgpeth commented
/test all

2021-08-23 14:44 UTC, anniehedgpeth commented
/test all

2021-08-23 22:06 UTC, anniehedgpeth commented
/test all

2021-09-01 16:01 UTC, anniehedgpeth commented
/test all destroy=false

2021-09-01 18:29 UTC, aaron-lane commented
/test all destroy=false

2021-09-01 19:45 UTC, anniehedgpeth commented
/test all destroy=false

2021-09-01 20:18 UTC, anniehedgpeth commented
/destroy all

2021-09-01 20:48 UTC, anniehedgpeth commented
/test all

2021-09-02 15:30 UTC, anniehedgpeth commented
/test all destroy=false

2021-09-02 19:54 UTC, anniehedgpeth commented
/test all destroy=false

2021-09-02 20:39 UTC, anniehedgpeth commented
/test all destroy=false

2021-09-02 21:11 UTC, anniehedgpeth commented
/destroy all

2021-09-08 15:46 UTC, aaron-lane requested changes
Here are my initial thoughts. We can cover some of these suggestions in future PRs as this one is quite lengthy already. Let me know what you think!

2021-09-08 15:46 UTC, aaron-lane commented on README.md
> +| `certificate_name` | Name of the PFX formatted CERTIFICATE found in the Azure Key Vault (PEM certificates are not currently supported by Azure) | **Required** <br>This certificate is used for TLS.
> It will also be placed on the Application Gateway if that is your load balancing option

I think using this same certificate input on app gateway and the VMSS worked because we tested with a wildcard certificate, but we can't assume this same input will be valid to use in both places simultaneously. Assuming that's correct, we will need two optional inputs to manage the app gateway and VMSS certificates separately (though continue passing the same wildcard certificate to both in the tests).

2021-09-08 15:46 UTC, aaron-lane commented on README.md
> +| `certificate_name` | Name of the PFX formatted CERTIFICATE found in the Azure Key Vault (PEM certificates are not currently supported by Azure) | **Required** <br>This certificate is used for TLS.
> If you do not need to customize your certificates to add an intermediate or root, then you will not need to use the `TlsBootstrap*` variables

Most of the `TLSBootstrap*` configuration settings are presently hard-coded so I think this statement can be removed for clarity.

2021-09-08 15:46 UTC, aaron-lane commented on main.tf
> +  tfe_bootstrap_cert_name = var.tfe_bootstrap_cert_secret_name == null ? upper(module.service_accounts.certificate[0].thumbprint) : var.tfe_bootstrap_cert_secret_name
The `service_accounts` module does not have a `certificate` output. `terraform validate` seems to miss this issue because of the ternary operator.

2021-09-08 15:46 UTC, aaron-lane commented on main.tf
> +  tfe_bootstrap_key_name  = var.tfe_bootstrap_key_secret_name == null ? upper(module.service_accounts.certificate[0].thumbprint) : var.tfe_bootstrap_key_secret_name
Same issue here about `module.service_accounts.certificate`. Also, should this be the key fingerprint rather than also the certificate fingerprint?

2021-09-08 15:46 UTC, aaron-lane commented on README.md
> +| `proxy_cert_name` | Name for the stored proxy certificate bundle | **Optional** <br>This variable is only for the name of the certificate file once it is added to the instance(s).<br><br/>If this v
We need to consider reconcile the `user_data_ca` input and the `proxy_cert*` inputs. The latter two are named a bit misleading, as they are actually inputs for a CA certificate bundle, and currently `proxy_cert_name` causes the value of `ca_certs` defined by `user_data_ca` in `user_data` HCL to be overwritten later in `tfe.sh.tpl`. I think they were conflated with the concept of a proxy because we were originally testing with untrusted certificates for mitmproxy. 

I suggest that we replace these three inputs with a single `ca_cert_secret_name` that we can use in the existing `proxy_cert` shell function (which would also be renamed). `proxy_ip` would remain unchanged as that is a separate concept.

2021-09-08 15:55 UTC, anniehedgpeth commented on main.tf
> +  tfe_bootstrap_cert_name = var.tfe_bootstrap_cert_secret_name == null ? upper(module.service_accounts.certificate[0].thumbprint) : var.tfe_bootstrap_cert_secret_name
Good catch. The logic changed, and this was supposed to have been taking the values from `certificate_name`, but I'll need to change the output to the whole certificate, not just the name.

2021-09-08 16:04 UTC, anniehedgpeth commented on main.tf
> +  tfe_bootstrap_key_name  = var.tfe_bootstrap_key_secret_name == null ? upper(module.service_accounts.certificate[0].thumbprint) : var.tfe_bootstrap_key_secret_name
It's the certificate thumbprint, and the same one is used for both.

2021-09-08 16:07 UTC, anniehedgpeth commented on README.md
> +| `proxy_cert_name` | Name for the stored proxy certificate bundle | **Optional** <br>This variable is only for the name of the certificate file once it is added to the instance(s).<br><br/>If this v
Agreed. I didn't want to make any major changes to this until we added the `private-active-active` example.

2021-09-08 18:40 UTC, anniehedgpeth commented
/test all

2021-09-08 19:40 UTC, aaron-lane approved these changes

2021-09-08 19:45 UTC, merged