settings module poc 2
hashicorp/terraform-azurerm-terraform-enterprise pull request #142
Opened 2022-01-14 00:08 UTC by anniehedgpeth

## Background

Just a tester to see how the [POC](https://docs.google.com/document/d/1mqlE35M8zXIasGLnxeKGb9ozt0UnOoYVRr2Z7zhh1tM/edit#heading=h.gb4gcg7zw6kf) is shaking out.

2022-01-14 00:08 UTC, anniehedgpeth commented
/test all

2022-01-14 00:34 UTC, anniehedgpeth commented
I manually destroyed the RGs after the destroys failed.

2022-01-14 16:38 UTC, anniehedgpeth commented
/test all destroy=false

2022-01-14 21:14 UTC, anniehedgpeth commented
/destroy public-active-active

2022-01-14 22:43 UTC, anniehedgpeth commented
/destroy private-active-active

2022-01-14 22:43 UTC, anniehedgpeth commented
/destroy private-tcp-active-active

2022-01-18 23:32 UTC, anniehedgpeth commented
/test private-active-active destroy=false

2022-01-19 00:15 UTC, anniehedgpeth commented
/destroy private-active-active

2022-01-19 00:16 UTC, anniehedgpeth commented
/test private-tcp-active-active

2022-01-19 00:57 UTC, anniehedgpeth commented
/destroy private-tcp-active-active

2022-01-19 14:20 UTC, anniehedgpeth commented
/test all

2022-01-19 17:24 UTC, anniehedgpeth commented
/test private-tcp-active-active destroy=false

2022-01-19 17:57 UTC, anniehedgpeth commented
/destroy private-tcp-active-active

2022-01-19 18:03 UTC, anniehedgpeth commented
/test private-active-active destroy=false

2022-01-19 18:10 UTC, anniehedgpeth commented
/test private-tcp-active-active destroy=false

2022-01-19 19:15 UTC, anniehedgpeth commented
/destroy private-tcp-active-active

2022-01-19 19:28 UTC, anniehedgpeth commented
/destroy private-active-active

2022-01-19 21:27 UTC, anniehedgpeth commented
/test private-active-active

2022-01-19 22:18 UTC, anniehedgpeth commented
/destroy private-active-active

2022-01-19 22:19 UTC, anniehedgpeth commented
Many of the failures in the destroys are due to this issue: https://github.com/hashicorp/terraform-provider-azurerm/issues/5299

2022-01-20 23:27 UTC, anniehedgpeth commented
/test all destroy=false

2022-01-21 00:05 UTC, anniehedgpeth commented
/destroy all

2022-01-21 00:58 UTC, anniehedgpeth commented
/test all

2022-01-21 01:30 UTC, anniehedgpeth commented
/destroy public-active-active

2022-01-21 01:45 UTC, anniehedgpeth commented
/test public-active-active

2022-01-21 16:18 UTC, anniehedgpeth commented
/test all

2022-01-21 19:02 UTC, anniehedgpeth commented
/test private-active-active destroy=false
C'mon Azure, you can do this with no intermittent errors. I believe in you.

2022-01-21 20:34 UTC, anniehedgpeth commented
/destroy public-active-active

2022-01-26 18:41 UTC, aaron-lane requested changes
Just a few minor tweaks for consideration!

2022-01-26 18:41 UTC, aaron-lane commented on main.tf
> +  }
Note for posterity: we still need to determine how and when to use objects over primitive variables.

2022-01-26 18:41 UTC, aaron-lane commented on main.tf
> +  redis_enable_non_ssl_port = local.redis.enable_non_ssl_port
I've opened https://github.com/hashicorp/terraform-random-tfe-utility/pull/5 to remove this argument and instead infer `redis_port` from `redis_use_tls`. I think we can standardize this module on the `use_tls` argument to align with the settings.

2022-01-26 18:41 UTC, aaron-lane commented on modules/redis/outputs.tf
> +}
Outputs should use attributes of resources when possible, rather than returning variable inputs, as using variables won't affect the dependency graph as one may expect.

More generally, I think it would be preferable to have a single output of the entire `azurerm_redis_cache` resource, but it's not necessary to address at this point.

2022-01-26 19:36 UTC, anniehedgpeth commented on modules/redis/outputs.tf
> +}
Hey @aaron-lane, take a look at the latest commit and lmk if that's more in line with what you're thinking. If so, I'll test again (just don't want to run the tests if there are more changes I need to make).

2022-01-26 19:41 UTC, aaron-lane approved these changes
LGTM 🔴

2022-01-26 19:42 UTC, anniehedgpeth commented
/test all destroy=false

2022-01-26 19:45 UTC, sandrampeter approved these changes

2022-01-26 20:24 UTC, anniehedgpeth commented
/destroy all

2022-01-26 20:55 UTC, merged