Bastion vm fixture
hashicorp/terraform-azurerm-terraform-enterprise pull request #143
Opened 2022-01-20 17:40 UTC by anniehedgpeth

## Background

[Asana](https://app.asana.com/0/1181500399442529/1201469300087917/f)
This branch adds a fixture module for the creation of a bastion virtual machine. More details in the Asana task above.

## How Has This Been Tested

I tested the private-active-active test locally, but I will test again here and also test private-tcp-active-active, as they are the two that require bastion virtual machines.

## This PR makes me feel

![reusable](https://media.giphy.com/media/7zaPsodlQj8QX5QmtE/giphy.gif)

2022-01-20 17:43 UTC, anniehedgpeth commented
/test private-active-active destroy=false

2022-01-20 17:44 UTC, anniehedgpeth commented
/test private-tcp-active-active destroy=false

2022-01-20 17:50 UTC, anniehedgpeth commented
/test private-tcp-active-active destroy=false

2022-01-20 18:23 UTC, anniehedgpeth commented
/destroy private-active-active destroy=false

2022-01-20 18:30 UTC, anniehedgpeth commented
/destroy private-tcp-active-active

2022-01-21 15:50 UTC, aaron-lane requested changes
Nice work, surpassed only by the amazing feat of the tests running successfully on the first try 😮 

Beyond the one request below, we also need to drop [private-tcp-active-active/proxy.tf](https://github.com/hashicorp/terraform-azurerm-terraform-enterprise/blob/1df02291ef8485a213a3cb0b58333ee66d95fb1e/tests/private-tcp-active-active/proxy.tf).

2022-01-21 15:50 UTC, aaron-lane commented on fixtures/bastion_vm/README.md
> +While the root module of this repository gives you the option to create an [Azure Bastion](../modules/bastion/README.md) (as this is the recommended method for accessing your TFE instance), there may
This line should be split up for improved gitability 🪘

2022-01-21 16:07 UTC, anniehedgpeth commented
> Nice work, surpassed only by the amazing feat of the tests running successfully on the first try 😮
> 
> Beyond the one request below, we also need to drop [private-tcp-active-active/proxy.tf](https://github.com/hashicorp/terraform-azurerm-terraform-enterprise/blob/1df02291ef8485a213a3cb0b58333ee66d95fb1e/tests/private-tcp-active-active/proxy.tf).

Ha, oh no, I deleted the looooong list of failed tests because I was tired of scrolling. 😆

2022-01-21 16:07 UTC, anniehedgpeth commented
> 



> > Nice work, surpassed only by the amazing feat of the tests running successfully on the first try 😮
> > Beyond the one request below, we also need to drop [private-tcp-active-active/proxy.tf](https://github.com/hashicorp/terraform-azurerm-terraform-enterprise/blob/1df02291ef8485a213a3cb0b58333ee66d95fb1e/tests/private-tcp-active-active/proxy.tf).
> 
> Ha, oh no, I deleted the looooong list of failed tests because I was tired of scrolling. 😆

Oh wait, wrong PR, yeah, this one was easy and only once.

2022-01-21 21:07 UTC, aaron-lane approved these changes
Sorry, I was waiting for `proxy.tf` to be removed when it's completely irrelevant to this work 😅

2022-01-21 21:10 UTC, merged