proxy-fixture
hashicorp/terraform-azurerm-terraform-enterprise pull request #159
Opened 2022-03-15 23:13 UTC by sandrampeter

## Background

[Asana](https://app.asana.com/0/1200681690870921/1201744486584884/f)

Locally tested with terraform plan

2022-03-16 14:38 UTC, anniehedgpeth requested changes
I think you might still be testing, but I thought I'd throw in these little things real quick.

2022-03-16 15:55 UTC, sandrampeter commented
/test private-tcp-active-active

2022-03-16 15:55 UTC, sandrampeter commented
/test private-tcp-active-active

2022-03-16 16:45 UTC, sandrampeter commented
/test private-tcp-active-active

2022-03-16 17:33 UTC, sandrampeter commented
/test private-tcp-active-active

2022-03-16 19:04 UTC, sandrampeter commented
/test private-tcp-active-active

2022-03-16 19:26 UTC, sandrampeter commented
/test private-tcp-active-active

2022-03-16 19:37 UTC, sandrampeter commented
/test private-tcp-active-active

2022-03-16 20:26 UTC, sandrampeter commented
/test private-active-active

2022-03-17 00:41 UTC, sandrampeter commented
/destroy private-tcp-active-active

2022-03-17 17:40 UTC, sandrampeter commented
/destroy private-tcp-active-active

2022-03-17 17:51 UTC, sandrampeter commented
/test private-tcp-active-active destroy=false

2022-03-17 19:35 UTC, sandrampeter commented
/destroy private-tcp-active-active

2022-03-17 19:46 UTC, sandrampeter commented
/test private-tcp-active-active destroy=false

2022-03-17 20:41 UTC, sandrampeter commented
/destroy private-tcp-active-active

2022-03-17 20:57 UTC, sandrampeter commented
/test private-tcp-active-active

2022-03-18 02:14 UTC, sandrampeter commented
/test private-tcp-active-active

2022-03-18 13:16 UTC, sandrampeter commented
/test private-tcp-active-active destroy=false

2022-03-18 13:49 UTC, sandrampeter commented
/destroy private-tcp-active-active

2022-03-18 14:02 UTC, sandrampeter commented
/test all

2022-03-18 14:56 UTC, sandrampeter commented
/test private-tcp-active-active

2022-03-18 15:44 UTC, sandrampeter commented
/destroy private-tcp-active-active

2022-03-18 16:58 UTC, sandrampeter commented
/test all

2022-03-22 14:42 UTC, sandrampeter commented
/test all

2022-03-24 03:49 UTC, sandrampeter commented
/test all

2022-03-28 17:07 UTC, anniehedgpeth requested changes
Looks good! Just need to update a couple of variable descriptions for Azure that were copied from the GCP module.

2022-03-28 17:07 UTC, anniehedgpeth commented on fixtures/test_proxy/variables.tf
> +  For GCP, the Terraform provider calls this value the secret_id and the GCP UI calls it the name.
Can you update this for Azure?

2022-03-28 17:07 UTC, anniehedgpeth commented on fixtures/test_proxy/variables.tf
> +  For GCP, the Terraform provider calls this value the secret_id and the GCP UI calls it the name.
Can you update this for Azure?

2022-03-28 18:13 UTC, sandrampeter commented on fixtures/test_proxy/variables.tf
> +  For GCP, the Terraform provider calls this value the secret_id and the GCP UI calls it the name.
done

2022-03-28 18:14 UTC, sandrampeter commented on fixtures/test_proxy/variables.tf
> +  For GCP, the Terraform provider calls this value the secret_id and the GCP UI calls it the name.
done

2022-03-28 18:20 UTC, anniehedgpeth approved these changes

2022-03-28 18:36 UTC, merged