Example standalone
hashicorp/terraform-azurerm-terraform-enterprise pull request #171
Opened 2022-05-12 21:38 UTC by sandrampeter

## Background

Standalone Examples :

[standalone_airgap](https://app.asana.com/0/1200681690870921/1202157051958514/f)

[standalone_airgap_dev](https://app.asana.com/0/1200681690870921/1202157051958513/f)

[standalone_mounted_disk](https://app.asana.com/0/1200681690870921/1202157051958515/f)

2022-05-16 22:37 UTC, sandrampeter commented
All tests pass, screenshots attached in ticket

2022-05-16 23:10 UTC, anniehedgpeth requested changes

2022-05-16 23:10 UTC, anniehedgpeth commented on examples/standalone_airgap_dev/README.md
> +- Mounted Disk production type
Should this be external?

2022-05-16 23:10 UTC, anniehedgpeth commented on examples/standalone_airgap_dev/main.tf
> +  create_bastion = true
Usually we wouldn't have both of these true, as you only need one or the other.

2022-05-16 23:10 UTC, anniehedgpeth commented on examples/standalone_airgap_dev/main.tf
>  module "standalone_airgap_dev" {
Would you mind alphabetizing these for consistency's sake?

2022-05-16 23:10 UTC, anniehedgpeth commented on examples/standalone_airgap_dev/ssh.tf
> +# Create files for SSH config.
```suggestion
# Create files for SSH config
# ---------------------------
```

2022-05-16 23:10 UTC, anniehedgpeth commented on examples/standalone_airgap_dev/terraform.tfvars.example
> +location                       = "region"
```suggestion
location                       = "Central US"
```

2022-05-16 23:10 UTC, anniehedgpeth commented on examples/standalone_mounted_disk/terraform.tfvars.example
> +location                       = "region"
```suggestion
location                       = "Central US"
```

2022-05-18 13:53 UTC, sandrampeter commented on examples/standalone_airgap_dev/main.tf
> +  create_bastion = true
updated

2022-05-18 13:54 UTC, sandrampeter commented on examples/existing-network/terraform.tfvars.example
> +location                             = "region"
for other examples, we decided to use "region" instead of explicit locations.

2022-05-18 16:41 UTC, anniehedgpeth commented on examples/existing-network/terraform.tfvars.example
> +location                             = "region"
Oh darn, can you change them to a specific region example?

2022-05-18 16:43 UTC, sandrampeter commented on examples/existing-network/terraform.tfvars.example
> +location                             = "region"
okay, np!

2022-05-18 16:48 UTC, anniehedgpeth requested changes

2022-05-18 16:48 UTC, anniehedgpeth commented on examples/standalone_airgap/main.tf
>    # Standalone, Mounted Disk Mode, Airgapped Installation Example
```suggestion
# Standalone, External Mode, Airgapped Installation Example
# ---------------------------------------------------------
```

2022-05-18 16:48 UTC, anniehedgpeth commented on examples/standalone_airgap/ssh.tf
> +#----------------------------
```suggestion
# Create files for SSH config
# ---------------------------
```

2022-05-18 16:48 UTC, anniehedgpeth commented on examples/standalone_airgap/ssh.tf
> +}
I'm curious why you chose to use SSH instead of the Azure Bastion for this example. Seems like Azure Bastion would be the more secure option, and we only suggest SSH for dev environments.

2022-05-18 16:48 UTC, anniehedgpeth commented on examples/standalone_airgap/terraform.tfvars.example
> +                           Description = "Standalone, Mounted Disk, Airgapped scenario"
```suggestion
                           Description = "Standalone, External Mode, Airgapped scenario"
```

2022-05-18 16:48 UTC, anniehedgpeth commented on examples/standalone_airgap/terraform.tfvars.example
> +location                = "region"
Again, this should be an actual example value.

2022-05-18 16:48 UTC, anniehedgpeth commented on examples/standalone_airgap_dev/main.tf
> +  enable_ssh = true
Here, I can see why you chose SSH over Azure Bastion, because we clearly call it out as a dev environment.

2022-05-18 17:29 UTC, sandrampeter commented on examples/standalone_airgap_dev/main.tf
> +  enable_ssh = true
you are right, removing ssh

2022-05-18 18:03 UTC, anniehedgpeth commented on examples/standalone_mounted_disk/terraform.tfvars.example
> +location                       = "region"
```suggestion
location                       = "Central US"
```

2022-05-18 18:04 UTC, anniehedgpeth approved these changes
I think this is good to go. I'd like to have @jkerry 's eyes on it, too, before merging.

2022-05-19 16:14 UTC, jkerry approved these changes
LGTM! thanks for getting this through

2022-05-19 16:25 UTC, merged