Fix Deprecation in Virtual Machine Scale Set
hashicorp/terraform-azurerm-terraform-enterprise pull request #209
Opened 2023-03-20 12:53 UTC by 0x46616c6b

## Background

This change will fix a deprecation in `azurerm_linux_virtual_machine_scale_set`:

```
│ Warning: Argument is deprecated
│ 
│   with module.vm.azurerm_linux_virtual_machine_scale_set.tfe_vmss,
│   on modules/vm/main.tf line 40, in resource "azurerm_linux_virtual_machine_scale_set" "tfe_vmss":
│   40:   scale_in_policy = var.vm_vmss_scale_in_policy
│ 
│ `scale_in_policy` will be removed in favour of the `scale_in` code block in
│ version 4.0 of the AzureRM Provider.
```

It replaces `var.scale_in_policy` with two new variables:

- `var.vm_vmss_scale_in_rule` (default: `"Default"`)
- `vm_vmss_scale_in_force_deletion_enabled` (default: `false`)

2023-03-20 19:39 UTC, anniehedgpeth requested changes
Thank you for your contribution! It's much appreciated. 

In order to merge this pull request, I would like to kindly ask for a couple of additional changes to make it functional within this repo and for the tests to pass. 

Please update the root module to include these new variables in the:

- [ ] `variables.tf` ([here](https://github.com/hashicorp/terraform-azurerm-terraform-enterprise/blob/main/variables.tf))
- [ ] module call to use the vm module ([here](https://github.com/hashicorp/terraform-azurerm-terraform-enterprise/blob/main/main.tf#L281-L327))

After that is complete, I will run the tests. 

Thank you!!!

2023-03-21 09:44 UTC, 0x46616c6b commented
Sure, I updated the usage of the module. Thanks for your quick review!

2023-03-21 16:56 UTC, anniehedgpeth requested changes
I'm requesting two more tiny, little changes, and then I'll run the tests. :)

2023-03-21 16:56 UTC, anniehedgpeth commented on modules/vm/variables.tf
> +  default     = false
```suggestion
```
Same here. Let's leave it to the root module to default the values.

2023-03-22 15:04 UTC, anniehedgpeth commented
/test all

2023-03-22 15:59 UTC, anniehedgpeth commented
/test private-tcp-active-active destroy=false

2023-03-22 17:51 UTC, anniehedgpeth approved these changes
Thanks for the changes! This looks great!

These two tests are failing for an unrelated reason for which I've already investigated and will submit a follow-up pull request to fix.

2023-03-22 17:51 UTC, merged